{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "soulmatting-auth-service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "soulmatting-auth-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "soulmatting-auth-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: soulmatting
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 5432  # PostgreSQL
        - protocol: TCP
          port: 6379  # Redis
    - to: []
      ports:
        - protocol: TCP
          port: 53   # DNS
        - protocol: UDP
          port: 53   # DNS
        - protocol: TCP
          port: 443  # HTTPS
        - protocol: TCP
          port: 80   # HTTP
{{- end }}