packages:
  - apps/*
  - packages/*
  - services/*
  - tools/*

catalog:
  '@nestjs/common': ^10.3.0
  '@nestjs/core': ^10.3.0
  '@nestjs/jwt': ^10.2.0
  '@nestjs/microservices': ^10.3.0
  '@nestjs/passport': ^10.0.3
  '@nestjs/platform-express': ^10.3.0
  '@nestjs/platform-socket.io': ^10.3.0
  '@nestjs/swagger': ^7.2.0
  '@nestjs/testing': ^10.3.0
  '@nestjs/websockets': ^10.3.0
  '@prisma/client': ^5.8.0
  '@supabase/supabase-js': ^2.38.0
  '@types/jest': ^29.5.11
  '@types/node': ^20.11.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  '@typescript-eslint/eslint-plugin': ^6.19.0
  '@typescript-eslint/parser': ^6.19.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  eslint: ^8.56.0
  jest: ^29.7.0
  next: ^14.1.0
  prettier: ^3.2.4
  prisma: ^5.8.0
  react: ^18.2.0
  react-dom: ^18.2.0
  reflect-metadata: ^0.2.1
  rxjs: ^7.8.1
  typescript: ^5.3.3

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
