packages:
  - apps/*
  - packages/*
  - services/*
  - tools/*

catalog:
  '@nestjs/common': ^10.4.20
  '@nestjs/core': ^10.4.20
  '@nestjs/jwt': ^10.2.0
  '@nestjs/microservices': ^10.4.20
  '@nestjs/passport': ^10.0.3
  '@nestjs/platform-express': ^10.4.20
  '@nestjs/platform-socket.io': ^11.1.6
  '@nestjs/swagger': ^7.4.2
  '@nestjs/testing': ^10.4.20
  '@nestjs/websockets': ^10.4.20
  '@prisma/client': ^5.22.0
  '@supabase/supabase-js': ^2.56.0
  '@types/jest': ^29.5.14
  '@types/node': ^20.19.11
  '@types/react': ^18.3.24
  '@types/react-dom': ^18.3.7
  '@typescript-eslint/eslint-plugin': 6.21.0
  '@typescript-eslint/parser': 6.21.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.2
  eslint: 8.57.1
  jest: ^29.7.0
  next: ^14.1.0
  prettier: ^3.2.4
  prisma: ^5.22.0
  react: ^18.3.1
  react-dom: ^18.3.1
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  typescript: ^5.9.2

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
