# SoulMatting Auth Service - Production Environment
# Author: Kim Hsiao
# Version: 1.0.0
# Created: 2024-01-20
# Last Updated: 2024-01-20

# =============================================================================
# Application Configuration
# =============================================================================
app:
  environment: production

# =============================================================================
# Image Configuration
# =============================================================================
image:
  repository: ghcr.io/kimhsiao/soulmatting/auth-service
  tag: latest
  pullPolicy: IfNotPresent

# =============================================================================
# Deployment Configuration
# =============================================================================
deployment:
  replicaCount: 3

# =============================================================================
# Ingress Configuration
# =============================================================================
ingress:
  hosts:
    - host: auth.soulmatting.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: soulmatting-auth-service-prod-tls
      hosts:
        - auth.soulmatting.com

# =============================================================================
# Resource Management
# =============================================================================
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# =============================================================================
# Auto Scaling
# =============================================================================
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# =============================================================================
# Environment Variables
# =============================================================================
env:
  NODE_ENV: production
  LOG_LEVEL: warn

# =============================================================================
# Pod Disruption Budget
# =============================================================================
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# =============================================================================
# Monitoring
# =============================================================================
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

# =============================================================================
# External Dependencies
# =============================================================================
redis:
  enabled: false # Use external Redis cluster in production

postgresql:
  enabled: false # Use external PostgreSQL cluster in production
