# SoulMatting Web Frontend - Staging Values
# Author: Kim Hsiao
# Version: 1.0.0
# Created: 2024-01-20
# Last Updated: 2024-01-20

# =============================================================================
# Application Configuration
# =============================================================================
app:
  environment: staging

# =============================================================================
# Image Configuration
# =============================================================================
image:
  pullPolicy: Always

# =============================================================================
# Deployment Configuration
# =============================================================================
deployment:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

# =============================================================================
# Ingress Configuration
# =============================================================================
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: staging-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Staging Environment'
  hosts:
    - host: staging.soulmatting.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: staging-soulmatting-com-tls
      hosts:
        - staging.soulmatting.com

# =============================================================================
# Resource Management
# =============================================================================
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# =============================================================================
# Auto Scaling
# =============================================================================
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# =============================================================================
# Environment Variables
# =============================================================================
env:
  NODE_ENV: staging
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  LOG_LEVEL: "debug"
  ENABLE_ANALYTICS: "false"
  ENABLE_MONITORING: "true"
  ENABLE_DEBUG: "true"

# =============================================================================
# ConfigMap Data
# =============================================================================
configMap:
  data:
    NEXT_PUBLIC_APP_NAME: "SoulMatting (Staging)"
    NEXT_PUBLIC_APP_VERSION: "1.0.0-staging"
    NEXT_PUBLIC_API_URL: "https://api-staging.soulmatting.com"
    NEXT_PUBLIC_WS_URL: "wss://ws-staging.soulmatting.com"
    NEXT_PUBLIC_SUPABASE_URL: "https://staging-soulmatting.supabase.co"
    NEXT_PUBLIC_CDN_URL: "https://cdn-staging.soulmatting.com"
    NEXT_PUBLIC_SENTRY_DSN: "https://your-staging-sentry-dsn@sentry.io/project-id"
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: "G-STAGING-XXXX"
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "your-staging-google-maps-key"
    NEXT_PUBLIC_FACEBOOK_APP_ID: "your-staging-facebook-app-id"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: "your-staging-google-client-id"
    NEXT_PUBLIC_ENVIRONMENT: "staging"
    NEXT_PUBLIC_FEATURE_FLAGS: "premium:true,matching:true,messaging:true,debug:true"
    NEXT_PUBLIC_DEBUG_MODE: "true"

# =============================================================================
# Node Selection
# =============================================================================
nodeSelector:
  node-type: web
  environment: staging

tolerations:
  - key: "staging-workload"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - soulmatting-web
        topologyKey: kubernetes.io/hostname

# =============================================================================
# Pod Disruption Budget
# =============================================================================
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# =============================================================================
# Network Policy
# =============================================================================
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 3000
    - from: []  # Allow all for staging debugging
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to: []  # Allow all egress for staging

# =============================================================================
# Monitoring
# =============================================================================
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /api/metrics
    port: 3000
    labels:
      environment: staging
      team: platform
  
  prometheusRule:
    enabled: true
    rules:
      - alert: StagingWebAppDown
        expr: up{job="soulmatting-web",environment="staging"} == 0
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "SoulMatting Web App is down in staging"
          description: "SoulMatting Web App has been down for more than 5 minutes in staging."
      
      - alert: StagingWebAppHighErrorRate
        expr: rate(http_requests_total{job="soulmatting-web",environment="staging",status=~"5.."}[5m]) > 0.1
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High error rate in SoulMatting Web App staging"
          description: "Error rate is above 10% for more than 10 minutes in staging."
      
      - alert: StagingWebAppHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="soulmatting-web",environment="staging"}[5m])) > 5
        for: 10m
        labels:
          severity: info
          team: platform
        annotations:
          summary: "High latency in SoulMatting Web App staging"
          description: "95th percentile latency is above 5 seconds for more than 10 minutes in staging."

# =============================================================================
# Dependencies
# =============================================================================
redis:
  enabled: true
  auth:
    enabled: true
    password: "staging-redis-password"
  master:
    persistence:
      enabled: true
      size: 4Gi
      storageClass: "standard"
  replica:
    replicaCount: 1
    persistence:
      enabled: false

postgresql:
  enabled: true
  auth:
    postgresPassword: "staging-postgres-password"
    database: "soulmatting_staging"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard"
  readReplicas:
    replicaCount: 0