# SoulMatting Platform - Umbrella Helm Chart
# Author: Kim Hsiao
# Version: 1.0.0
# Created: 2024-01-20
# Last Updated: 2024-01-20

apiVersion: v2
name: soulmatting
description: A Helm umbrella chart for SoulMatting Platform - Complete microservices dating application
type: application
version: 0.1.0
appVersion: '1.0.0'

keywords:
  - soulmatting
  - dating
  - microservices
  - platform
  - nodejs
  - react

home: https://github.com/kimhsiao/soulmatting
sources:
  - https://github.com/kimhsiao/soulmatting

maintainers:
  - name: Kim Hsiao
    email: kim@soulmatting.com
    url: https://github.com/kimhsiao

dependencies:
  # Frontend Web Application
  - name: soulmatting-web
    version: '1.0.0'
    repository: 'file://../web'
    condition: web.enabled

  # Backend Microservices
  - name: soulmatting-auth-service
    version: '1.0.0'
    repository: 'file://../auth-service'
    condition: auth.enabled

  - name: soulmatting-user
    version: '1.0.0'
    repository: 'file://../user'
    condition: user.enabled

  - name: soulmatting-match
    version: '1.0.0'
    repository: 'file://../match'
    condition: match.enabled

  - name: soulmatting-communication
    version: '1.0.0'
    repository: 'file://../communication'
    condition: communication.enabled

  - name: soulmatting-media
    version: '1.0.0'
    repository: 'file://../media'
    condition: media.enabled

  - name: soulmatting-notification
    version: '1.0.0'
    repository: 'file://../notification'
    condition: notification.enabled

  - name: soulmatting-search
    version: '1.0.0'
    repository: 'file://../search'
    condition: search.enabled

  - name: soulmatting-payment
    version: '1.0.0'
    repository: 'file://../payment'
    condition: payment.enabled

  - name: soulmatting-analytics
    version: '1.0.0'
    repository: 'file://../analytics'
    condition: analytics.enabled

  # Shared Infrastructure
  - name: redis
    version: '17.15.6'
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: postgresql
    version: '12.12.10'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: elasticsearch
    version: '19.13.13'
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
